facturacio/urls.py
from django.conf.urls import patterns, include, url
from .views import EmpresesPendingRevisionUpdateView, \
    EmpresesPendingRevisionListView


urlpatterns = patterns(

    'facturacio.views',

    url(r'^llistat_quotes_trimestrals/$',                    'llistat_quotes_trimestrals',   name='llistat_quotes_trimestrals'),

    url(r'^validar_empresa/(?P<empresa_id>\d+)/$',           'validar_empresa',              name='validar_empresa'),
    url(r'^modificar_empresa/(?P<pk>\d+)/$',    EmpresesPendingRevisionUpdateView.as_view(), name='modificar_empresa'),
    url(r'^validacio_empreses/$',               EmpresesPendingRevisionListView.as_view(),   name='validacio_empreses'),
    
    url(r'^buscar_empresa/(?P<kind>\w+)/(?P<nif>\w+)$',      'buscar_empresa',               name="buscar_empresa"),
    url(r'^buscar_empresa/(?P<kind>\w+)$',                   'buscar_empresa',               name="buscar_empresa"),

    url(r'^crear_factura_emesa/$',                           'crear_factura_emesa',          name='crear_factura_emesa'),
    url(r'^crear_factura_emesa/(?P<id_client>\d+)$',         'crear_factura_emesa',          name='crear_factura_emesa'),
    url(r'^linies_factura_emesa/(?P<id_factura>\d+)$',       'editar_linies_factura_emesa',  name='editar_linies_factura_emesa'),
    url(r'^confirmar_factura_emesa/(?P<id_factura>\d+)$',    'confirmar_factura_emesa',      name='confirmar_factura_emesa'),
    url(r'^veure_factura_emesa/(?P<id_factura>\d+)$',        'veure_factura_emesa',          name='veure_factura_emesa'),

    url(r'^crear_factura_rebuda/$',                          'crear_factura_rebuda',         name='crear_factura_rebuda'),
    url(r'^crear_factura_rebuda/(?P<id_proveidor>\d+)$',     'crear_factura_rebuda',         name='crear_factura_rebuda'),
    url(r'^linies_factura_rebuda/(?P<id_factura>\d+)$',      'editar_linies_factura_rebuda', name='editar_linies_factura_rebuda'),
    url(r'^veure_factura_rebuda/(?P<id_factura>\d+)$',       'veure_factura_rebuda',         name='veure_factura_rebuda'),
    url(r'^validacio_factures_rebudes/$',                    'validacio_factures_rebudes',   name='validacio_factures_rebudes'),

    url(r'^resum_facturacio_projecte/$',                     'resum_facturacio_projecte',    name='resum_facturacio_projecte'),
    url(r'^resum_facturacio_projecte/(?P<id_projecte>\d+)$', 'resum_facturacio_projecte',    name='resum_facturacio_projecte'),

    url(r'^moviments/$',                                     'llistat_moviments',            name='moviments'),
    url(r'^moviments/(?P<id_projecte>\d+)$',                 'llistat_moviments',            name='moviments'),

    url(r'^llistat_projectes_autoocupats/$',                 'llistat_projectes_autoocupats', name='llistat_projectes_autoocupats'),

    url(r'^facturacio_per_proveidor/$', 'volum_facturacio_empresa', kwargs=dict(tipus='proveidor'), name='facturacio_per_proveidor'),
    url(r'^facturacio_per_client/$',    'volum_facturacio_empresa', kwargs=dict(tipus='client'),    name='facturacio_per_client'),

    url(r'^importar_extracte_bancari/$',                  'importar_extracte_bancari',             name="importar_extracte_bancari"),
    url(r'^llistat_moviments_extracte_descartats/tots/$', 'llistat_moviments_extracte_descartats', kwargs=dict(tots=True), name='llistat_moviments_descartats_tots'),
    url(r'^llistat_moviments_extracte_descartats/$',      'llistat_moviments_extracte_descartats', name='llistat_moviments_descartats'),

    url(r'^conciliacio_automatica_factures/$',
        'conciliacio_automatica', name='conciliacio_automatica'),

    url(r'^conciliacio_manual/$',
        'conciliacio_manual', name='conciliacio_manual'),

    url(r'^conciliacio_manual/(?P<compte_projecte>COOP\d{4})$',
        'conciliacio_manual_projecte', name='conciliacio_manual_projecte'),

    url(r'^conciliacio_manual/(?P<numero_factura>\d{4}/\d{6})$',
        'conciliacio_manual_factura', name='conciliacio_manual_factura'),

)

gestioci/urls.py
from django.conf import settings
from django.conf.urls import include, patterns, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = patterns(
    '',

    # Default Django Auth
    # https://docs.djangoproject.com/en/1.8/topics/auth/default/#built-in-auth-views
    url(r'^accounts/', include([
        url(r'^login/$', auth_views.login, name='login'),
        url(r'^logout/$', auth_views.logout, {'next_page': '/accounts/login/'}, name='logout'),

        url(r'^password/', include([
            url(r'^change/$', auth_views.password_change, name='password_change'),
            url(r'^change/done/$', auth_views.password_change_done, name='password_change_done'),

            url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.password_reset_confirm, name='password_reset_confirm'),
            url(r'^reset/complete/$', auth_views.password_reset_complete, name='password_reset_complete'),
            url(r'^reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
            url(r'^reset/$', auth_views.password_reset, { 'html_email_template_name': 'registration/password_reset_email.html' }, name='password_reset'),
        ])),
    ])),


    # Apps
    url(r'^socies/alta/', include('alta_socies.urls', namespace='alta_socies')),
    url(r'^socies/',      include('socies.urls', namespace='socies')),
    url(r'^facturacio/',  include('facturacio.urls', namespace='facturacio')),

    url(r'^admin/',       include(admin.site.urls)),

    url(r'^inici/$',       'inici.views.inici',                      name='inici'),
    url(r'^ge/$',          'inici.views.dashboard_gestio_economica', name='dashboard_gestio_economica'),
    url(r'^pao/$',         'facturacio.views.dashboard_facturacio',  name='dashboard_projecte_autoocupat'),
    url(r'^sc/$',          'socies.views.dashboard_socia_cooperativa',           name='dashboard_socia_cooperativa'),
    url(r'^style-guide/$', 'inici.views.styleguide',                 name='styleguide'),

    url(r'^/?$',            'inici.views.index',                      name='index'),
)

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns(
        '',
        (
            r'^media/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}
        ),
    )

# Implement docutils features
if settings.ENV == 'development':
    urlpatterns += patterns(
        '',
        ( r'^admin/doc/', include('django.contrib.admindocs.urls')),
        )

socies/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns(
    'socies.views',
    url(r'^cerca_persones/$', 'cerca_persones', name='cerca_persones'),
)

facturacio/models.py
# coding=utf-8
import re

from datetime import timedelta, date
from decimal import Decimal

from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.db import models, transaction
from django.db.models import Max, Sum, Min
from django.utils import timezone

from projectes.models import ProjecteAutoocupat
from empreses.models import Empresa, Cooperativa
from socies.models import PersonaUsuaria, Persona
from gestioci.settings import auth_groups
from .helpers import calcular_trimestre


class QuotaTrimestral(models.Model):

    base_imposable_minima = models.DecimalField(max_digits=8, decimal_places=2)
    import_quota_trimestral = models.DecimalField(max_digits=8, decimal_places=2)
    data_vigor = models.DateField(verbose_name=u"data d'entrada en vigor")

    class Meta:
        verbose_name_plural = 'quotes trimestrals'


# TODO això hauria d'anar a "Soci" (quan es defineixi aquesta abstracció)
# o si nomes aplica a projectes autoocupats s'haurien de canviar els noms de
# QuotaTrimestral i d'aquesta funció per fer-ho palès
def trobar_quota_trimestral(data, base_imposable):

    # la taula de quotes que aplica és la que té la data d'entrada en vigor màxima tal que
    # la data d'entrada en vigor és menor o igual a la data en que es vol fer el moviment
    data_vigor = QuotaTrimestral.objects.filter(data_vigor__lte=data).aggregate(Max('data_vigor'))['data_vigor__max']

    if data_vigor is None:
        raise ValueError(u"No hi ha quotes trimestrals definides per aquesta data (%s)" % data.isoformat())

    # donada aquesta data d'entrada en vigor, trobem el tram de facturació i la quota trimestral que aplica:
    # de tots els trams per imports inferiors o iguals a la facturació que s'indica, ens quedem amb el que
    # correspon a l'import més gran
    trobar_quota = QuotaTrimestral.objects.filter(data_vigor=data_vigor)
    trobar_quota = trobar_quota.filter(base_imposable_minima__lte=base_imposable)
    trobar_quota = trobar_quota.order_by('-base_imposable_minima')

    trobar_quota = list(trobar_quota)

    if len(trobar_quota):
        return trobar_quota[0].import_quota_trimestral

    raise ValueError(u"Manca un tram amb 'base imposable minima' = 0 a 'quota trimestral' "
                     u"per 'data d'entrada en vigor' = %s" % data_vigor)


class Factura(models.Model):

    FORMA_PAGAMENT_EFECTIU = 'efectiu'
    FORMA_PAGAMENT_TRANSFERENCIA = 'transferencia'

    FORMES_DE_PAGAMENT = (
        (FORMA_PAGAMENT_EFECTIU, u"En efectiu"),
        (FORMA_PAGAMENT_TRANSFERENCIA, u"Gestiona la cooperativa"),
    )

    projecte = models.ForeignKey(ProjecteAutoocupat)

    proveidor = models.ForeignKey(Empresa, related_name='factures_emeses')
    client = models.ForeignKey(Empresa, related_name='factures_rebudes')

    data = models.DateField()

    base_total = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    iva_total = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    import_total = models.DecimalField(default=0, max_digits=8, decimal_places=2)

    data_venciment = models.DateField(null=True, blank=True)
    forma_de_pagament = models.CharField(default=FORMA_PAGAMENT_EFECTIU, max_length=16, choices=FORMES_DE_PAGAMENT)

    def _actualitzar_camps_calculats(self):
        """
        * actualitza els camps calculats de Factura.
        * no crida a save() en acabar, pq aquesta funció s'ha de 'overload' a
        les classes que en deriven, FacturaEmesa i FacturaRebuda, i es allà a
        on s'espera que es cridi el save()
        """

        client_es_cooperativa = Cooperativa.objects.filter(pk=self.client_id).exists()
        proveidor_es_cooperativa = Cooperativa.objects.filter(pk=self.proveidor_id).exists()

        if client_es_cooperativa and proveidor_es_cooperativa:
            raise Exception(u"La factura és invàlida: el client i el proveïdor són cooperatives")

        if not (client_es_cooperativa or proveidor_es_cooperativa):
            raise Exception(u"La factura és invàlida: no implica cap cooperativa, ni com a client ni com a proveïdor")

        if not self.pertany_a_trimestre_obert():
            raise Exception(u"La factura no es pot editar: correspon a un trimestre que no esta obert")

        self.base_total = Decimal('0.00')
        self.iva_total = Decimal('0.00')
        self.import_total = Decimal('0.00')

        for l in self.liniafactura_set.all():
            self.base_total += l.base_total
            self.iva_total += l.iva_total
            self.import_total += l.import_total

    def usuari_pot_editar(self, user):

        try:
            persona = PersonaUsuaria.objects.filter(usuari=user).first().persona
            self.projecte.membres_de_referencia.get(pk=persona.pk)
            return True

        except PersonaUsuaria.DoesNotExist, Persona.DoesNotExist:
            return False

    def pertany_a_trimestre_obert(self):

        trimestre = Trimestre.trobar_trimestre(self.data)
        assert trimestre  # no s'hauria d'haver pogut crear una factura en un trimestre que no existeix

        return trimestre.obert

    def save(self, *args, **kwargs):
        if (self.client and self.client.pendent_de_revisio) or (self.proveidor and self.proveidor.pendent_de_revisio):
            raise Exception(u"La factura és invàlida: no pot implicar una empresa que no ha estat validada per GE")
        super(Factura, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = u"factures"


class SequenciaNumeroFacturaEmesa(models.Model):

    year = models.SmallIntegerField(primary_key=True)
    value = models.IntegerField()

    @staticmethod
    @transaction.atomic
    def incrementa_i_retorna_seguent_numero(data):
        sequencia = SequenciaNumeroFacturaEmesa.objects.select_for_update().get(year=data.year)
        sequencia.value += 1
        sequencia.save()
        return sequencia.value

    @staticmethod
    def crear_sequencies_necessaries():
        """
        inicialitza a 1 les seqüències per als propers anys;
        la idea és no haver d'inicialitzar la seqüència per cada any
        en el moment de generar la primera factura; com que els anys
        es creen per avançat, d'aquesta manera s'esquiva el problema
        de concurrència que requeriria un "lock" explícit que caldria
        en el supòsit que evitem d'aquesta manera.

        aquest mètode està pensat per ser cridat des d'un cron job.
        """
        years_in_advance = 5
        current_year = timezone.localtime(timezone.now()).date().year
        farthest_year = SequenciaNumeroFacturaEmesa.objects.all().aggregate(Max('year'))['year__max']
        if farthest_year is None:
            farthest_year = current_year - 1
        for year in range(farthest_year + 1, max(current_year + years_in_advance, farthest_year) + 1):
            SequenciaNumeroFacturaEmesa.objects.create(year=year, value=1)


class FacturaEmesa(Factura):

    ESTAT_EMESA = 'emesa'
    ESTAT_COBRADA = 'cobrada'

    ESTATS = (
        (ESTAT_EMESA, u"Pendent de cobrar"),
        (ESTAT_COBRADA, u"Cobrada"),
    )

    numero = models.CharField(max_length=11, blank=True, null=True)
    estat = models.CharField(max_length=16, choices=ESTATS, default=ESTAT_EMESA)
    req_total = models.DecimalField(default=0, max_digits=8, decimal_places=2)  # recàrrec d'equivalència

    @transaction.atomic
    def assignar_numero_sequencia(self):
        n = SequenciaNumeroFacturaEmesa.incrementa_i_retorna_seguent_numero(self.data)
        self.numero = '%d/%06d' % (self.data.year, n)
        self.save()

    def save(self, *args, **kwargs):
        self._actualitzar_camps_calculats()
        self.req_total = Decimal('0.00')
        for l in self.liniafactura_set.all():
            self.req_total += l.req_total
        super(FacturaEmesa, self).save(*args, **kwargs)

    def calcular_resums(self):

        linies = self.liniafactura_set

        resum_iva = linies.values('tipus_iva').annotate(base_total=Sum('base_total'), iva_total=Sum('iva_total')).order_by('tipus_iva')
        resum_req = linies.values('tipus_req').annotate(base_total=Sum('base_total'), req_total=Sum('req_total')).order_by('tipus_req')
        resum_totals = linies.aggregate(Sum('base_total'), Sum('iva_total'), Sum('req_total'))

        import_total = sum([resum_totals[k] for k in resum_totals.keys()])
        base_total = resum_totals['base_total__sum']
        iva_total = resum_totals['iva_total__sum']
        req_total = resum_totals['req_total__sum']

        assert import_total == self.import_total
        assert base_total == self.base_total
        assert iva_total == self.iva_total
        assert req_total == self.req_total

        if len(resum_req) == 1:
            if resum_req[0]['tipus_req'] == Decimal('0.00'):
                resum_req = None

        return resum_iva, resum_req, resum_totals

    class Meta:
        verbose_name_plural = u"factures emeses"


class FacturaRebuda(Factura):

    ESTAT_REBUDA = 'rebuda'        # s'ha creat la factura al portal del soci
    ESTAT_ACCEPTADA = 'acceptada'  # s'ha rebut la factura a GE (en paper) i s'ha acceptat per la comptabilitat
    ESTAT_REBUTJADA = 'rebutjada'  # no s'ha rebut a GE i/o s'ha considerat que no és cap factura vàlida

    ESTATS = (
        (ESTAT_REBUDA, u"Pendent de revisió"),
        (ESTAT_ACCEPTADA, u"Acceptada"),
        (ESTAT_REBUTJADA, u"Rebutjada"),
    )

    numero = models.CharField(max_length=64)

    irpf_total = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    tipus_irpf = models.DecimalField(default=0, max_digits=4, decimal_places=2,
                                     verbose_name=u"retenció per l'IRPF",
                                     help_text=u"en tant percent")

    estat = models.CharField(max_length=16, choices=ESTATS, default=ESTAT_REBUDA)
    vist_i_plau_usuaria = models.ForeignKey(User, blank=True, null=True, related_name='+')

facturacio/templates/facturacio/conciliacio_manual_factura.html
{% extends "simple.html" %}
{% load gci_tags %}

{% block titol_a_capcalera %}Conciliació manual de la factura {{ numero_factura }}{% endblock %}

{% block content %}

<style>
    .ac { text-align: center; }
    .ar { text-align: right; }
</style>


<fieldset>
    <legend>Moviments a l'extracte bancari que mencionen la factura {{ numero_factura }}</legend>

    {% if moviments_extracte.count %}

        <legend>{{ moviments_extracte.count }} moviment{{ moviments_extracte.count|pluralize }}</legend>

        <table>
            <thead>
            <tr>
                <th class="ac">Compte</th>
                <th class="ac">Tipus</th>
                <th class="ac">Data</th>
                <th>Concepte</th>
                <th class="ac">Import</th>
                <th class="ac">Projecte</th>
                <th class="ac">Número factura</th>
                <th class="ac">Estat</th>
            </tr>
            </thead>
            <tbody>
            {% for m in moviments_extracte %}
            <tr>
                <td class="ac">{{ m.compte }}</td>
                <td class="ac">{{ m.tipus }}</td>
                <td class="ac">{{ m.data|date:'Y-m-d' }}</td>
                <td>{{ m.concepte }}</td>
                <td class="ar">{% currency_value m.quantitat %}</td>
                <td class="ac">{{ m.compte_projecte }}</td>
                {% if m.numero_factura %}
                    <td class="ac">{{ m.numero_factura }}</td>
                {% else %}
                    <td></td>
                {% endif %}
                <td class="ac">{{ m.get_status_display }}</td>
            </tr>
            {% endfor %}
            </tbody>
         </table>

    {% else %}

        <em style="color:red">No hi ha cap moviment a l'extracte que compleixi amb aquest criteri!</em>

    {% endif %}

</fieldset>


<fieldset>
    <legend>Dades de la factura {{ numero_factura }}</legend>

    {% if factura %}

        <table>
            <tr><th>Numero</th><td>{{ factura.numero }}</td></tr>
            <tr><th>Cooperativa</th><td>{{ factura.proveidor }}</td></tr>
            <tr><th>Projecte</th><td>{{ factura.projecte }}</td></tr>
            <tr><th>Data</th><td>{{ factura.data|date:'Y-m-d' }}</td></tr>
            <tr><th>Venciment</th><td>{{ factura.data_venciment|date:'Y-m-d' }}</td></tr>
            <tr><th>Import</th><td>{% currency_value factura.import_total %}</td></tr>
            <tr><th>Estat</th><td>{{ factura.get_estat_display }}</td></tr>
         </table>

    {% else %}

        <em style="color:red">No hi ha cap factura amb aquest número!</em>

    {% endif %}

</fieldset>


{%  endblock %}

facturacio/templates/facturacio/confirmar_factura_emesa.html
{% extends "simple.html" %}
{% load gci_tags %}

{#{% block titol_a_capcalera %}#}
{#{% endblock %}#}

{% block content %}

{# this should be above, inside titol_a_capcalera #}
<h1>Confirmació de la factura emesa
    {% if factura.numero %}{{ factura.numero }}{% else %}(proforma){% endif %}</h1>
{# end titol_a_capcalera #}

{% block explicacio_pas %}
    <div class="panel">
        <ul>
            {% if not factura.numero %}<li>Encara esteu treballant amb una factura «proforma».</li>{% endif %}
            <li>Empleneu les dades que calgui.</li>
            <li>Reviseu el desglós d'IVA, recàrrec d'equivalència i l'import total de la factura.</li>
            <li>Quan feu «generar» s'assignarà un número de la seqüència a la vostra factura, i deixarà de ser una «proforma».</li>
            <li>Un cop «generada», la factura ja no es podrà modificar. Per anul·lar-la haureu de generar-ne una altra d'import contrari.</li>
        </ul>
    </div>
{% endblock %}

<form method="POST">
    {% csrf_token %}

    <fieldset>
        <legend>Detalls del pagament</legend>
        <div class="medium-4 columns">
            {% form_field form.data_venciment %}
        </div>
        <div class="medium-4 columns">
            {% form_field form.forma_de_pagament %}
        </div>
    </fieldset>

<div class="row">
<div class="large-6 columns">

    <fieldset>
        <legend>IVA</legend>
        <table>
            <thead>
                <tr>
                    <th class="text-center">Tipus</th>
                    <th class="text-right">Base imposable</th>
                    <th class="text-right">Import</th>
                </tr>
            </thead>
            <tbody>
                {% for r in resum_iva %}
                <tr>
                    <td class="text-center">{{ r.tipus_iva }}%</td>
                    <td class="text-right">{{ r.base_total }}&nbsp;€</td>
                    <td class="text-right">{{ r.iva_total }}&nbsp;€</td>
                </tr>
                {% endfor %}
                {% if resum_iva.count > 1 %}
                <tr>
                    <th>total</th>
                    <th class="text-right">{{ base_total }}&nbsp;€</th>
                    <th class="text-right">{{ iva_total }}&nbsp;€</th>
                </tr>
                {% endif %}
            </tbody>
        </table>
    </fieldset>

    {% if req_total %}

    <fieldset>
        <legend>Recàrrec d'equivalència</legend>
        <table>
            <thead>
                <tr>
                    <th class="text-center">Tipus</th>
                    <th class="text-right">Base imposable</th>
                    <th class="text-right">Import</th>
                </tr>
            </thead>
            <tbody>
                {% for r in resum_req %}
                <tr>
                    <td class="text-center">{{ r.tipus_req }}%</td>
                    <td class="text-right">{{ r.base_total }}&nbsp;€</td>
                    <td class="text-right">{{ r.req_total }}&nbsp;€</td>
                </tr>
                {% endfor %}
                {% if resum_req.count > 1 %}
                <tr>
                    <th>total</th>
                    <th class="text-right">{{ base_total }}&nbsp;€</th>
                    <th class="text-right">{{ req_total }}&nbsp;€</th>
                </tr>
                {% endif %}
            </tbody>
        </table>

    </fieldset>

    {% endif %}

</div>
<div class="large-6 columns">

    <fieldset>
        <legend>Totals</legend>

        <table>
            <tr>
                <th>Base imposable</th>
                <td class="text-right">{{ factura.base_total }}&nbsp;€</td>
            </tr>
            <tr>
                <th>IVA</th>
                <td class="text-right">{{ factura.iva_total }}&nbsp;€</td>
            </tr>
            {% if factura.req_total %}
            <tr>
                <th>Recàrrec d'equivalència</th>
                <td class="text-right">{{ factura.req_total }}&nbsp;€</td>
            </tr>
            {% endif %}
            <tr>
                <th>Import a pagar</th>
                <th class="text-right">{{ factura.import_total }}&nbsp;€</th>
            </tr>
        </table>

    </fieldset>

</div>
</div>


    <a href="{% url "facturacio:editar_linies_factura_emesa" id_factura=factura.id %}" class="radius button">Editar línies</a>
    <button class="radius button" type="submit" name="anem_a" value="aqui">Desar</button>
    <button class="radius button" type="submit" name="anem_a" value="generar">Generar</button>
</form>

{% endblock %}

facturacio/templates/facturacio/importar_extracte_bancari.html
{% extends 'layout.html' %}
{% load gci_tags %}

{% block content %}
<div class="row">
  <div class="medium-10 columns medium-centered">
    <h1>{{ title }}</h1>
  </div>
</div>
<div class="row">
  <div class="medium-10 columns medium-centered">
    <fieldset>
      <legend> Introdueix un arxiu csv </legend>
      <form method="post" enctype="multipart/form-data">
	{% csrf_token %}
	{% non_field_errors form %}
	<div class="row">
	  <div class="medium-10 columns">
	    {% form_field form.file %}
	  </div>
	  <div class="medium-2 columns">
	    <button type="submit" class="radius success">Importar</button>
	  </div>
	</div>
      </form>
    </fieldset>
  </div>
</div>
{% endblock content %}
	

facturacio/templates/facturacio/llistat_empreses_pendents_revisio.html
{% extends "simple.html" %}
{% load gci_tags %}

{% block content %}
<h1>Llistat empresas pendents de revisió</h1>

<table>
  <thead>
    <tr>
      <th>NIF</th>
      <th>Nom Fiscal</th>
      <th>Telefon</th>
      <th>Correu-e</th>
      <th class="text-right">Modificar</th>
      <th class="text-right">Validar</th>
    </tr>
  </thead>
  <tbody>
    {% for empresa in empreses %}
    <tr>
      <td>{{ empresa.nif }}</td>
      <td>{{ empresa.nom_fiscal }}</td>
      <td>{{ empresa.telefon }}</td>
      <td>{{ empresa.email }}</td>
      <td class="text-center">
        <a href="{% url 'facturacio:modificar_empresa' empresa.pk %}"><i class="fa fa-pencil"></i></a>
      </td>
      <td class="text-center">
        <a href="{% url 'facturacio:validar_empresa' empresa.id %}"><i class="fa fa-sign-in"></i></a>
      </td>
    </tr>
    {% empty %}
    <tr>
      <td colspan="5" class="text-center">No hi ha cap empresa pendent de revisió</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

facturacio/templates/facturacio/llistat_moviments_extracte_descartats.html
{% extends 'layout.html' %}

{% block content %}
<div class="row">
  <div class="medium-10 columns medium-centered">
    <h1> {{ title }} </h1>
    {% if not tots %}
    <p> Aquest es un llistat dels 20 més recents moviments, per veure'ls tots fes click <a href="{% url 'facturacio:llistat_moviments_descartats_tots' %}" class="radius button info small">aquí</a></p>
    {% else %}
    <p> Aquest es un llistat de tots els moviments ordenats per antigüetat, per veure els més recents fes click <a href="{% url 'facturacio:llistat_moviments_descartats' %}" class="radius button info small">aquí</a></p>
    {% endif %}
  </div>
</div>
<div class="row">
  <div class="medium-10 columns medium-centered">
    <table>
      <thead>
	<tr>
	  <th>Data</tH>
	  <th>Compte</th>
	  <th>Tipus</th>
	  <th>Concepte</th>
	  <th>Quantitat</th>
	  <th>Compte Projecte</th>
	  <th>Numero factura</th>
	  <th>Comentaris</th>
	</tr>
      </thead>
      <tbody>
	{% for moviment in queryset %}
	<tr>
	  <td>{{ moviment.data }}</td>
	  <td>{{ moviment.compte }}</td>
	  <td>{{ moviment.tipus }}</td>
	  <td>{{ moviment.concepte }}</td>
	  <td>{{ moviment.quantitat }}</td>
	  <td>{{ moviment.compte_projecte }}</td>
	  <td>{{ moviment.numero_facutra }}</td>
	  <td>{{ moviment.comentaris }}</td>
	</tr>
	{% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock content %}