alta_socies/urls.py
from django.conf.urls import patterns, include, url

from .views import SessioMonedaListView, SessioMonedaCreateView
from .views import SessioAcollidaListView, SessioAcollidaCreateView, \
    SessioAcollidaUpdateView, SessioMonedaUpdateView, ProjecteCollectiuListView
from .views import ProcesAltaAutoocupatDetailView

urlpatterns = patterns(

    'alta_socies.views',


    # ------------
    # ALTRES ALTES
    # ------------

    url(r'^cooperativa/llistat_pendents/euros/$', 'llistat_socies_pendents_euro', name='llistat_socies_pendents_euro'),

    url(r'^cooperativa/llistat_pendents/ecos/$', 'llistat_socies_pendents_eco', name='llistat_socies_pendents_eco'),

    url(r'^cooperativa/llistat_pendents/hores/$', 'llistat_socies_pendents_temp', name='llistat_socies_pendents_temp'),

    url(r'^cooperativa/validar/(?P<id_socia>\d+)/$', 'validar_socia_pendent', name='validar_socia_pendent'),
    
    url(r'^cooperativa/(?P<pas>\d+)/$', 'proces_alta_socia_cooperativa', name='alta_socia_cooperativa'),
    
    url(r'^collectiu/dades_generals/$', 'proces_alta_projecte_collectiu_dades_generals', name='collectiu_dades_generals'),

    url(r'^collectiu/dades_concretes/$', 'proces_alta_projecte_collectiu_dades_concretes', name='collectiu_dades_concretes'),

    url(r'^collectiu/socies_afins/$', 'proces_alta_projecte_collectiu_socies_afins', name='collectiu_socies_afins'),

    url(r'^collectiu/llistat_pendents/euros/$', 'llistat_projectes_pendents_euro', name='llistat_projectes_pendents_euro'),

    url(r'^collectiu/llistat_pendents/ecos/$', 'llistat_projectes_pendents_eco', name='llistat_projectes_pendents_eco'),

    url(r'^collectiu/llistat_pendents/hores/$', 'llistat_projectes_pendents_temp', name='llistat_projectes_pendents_temp'),

    url(r'^collectiu/validar/(?P<id_projecte>\d+)/$', 'validar_projecte_pendent', name='validar_projecte_pendent'),
    url(r'^collectiu/llistat/$', ProjecteCollectiuListView.as_view(), name='llistat_projectes_collectius'),
    
    # -----------------
    # SOCIS AUTOOCUPATS
    # -----------------

    url(r'^rebutjar_proces_alta/(?P<id_proces>\d+)/$', 'rebutjar_proces_alta_autoocupat', name='rebutjar_proces'),

    url(r'^exportar_a_csv/$', 'exportar_a_csv', name='exportar_a_csv'),

    url(r'^autoocupat/resum/(?P<pk>\d+)/$', ProcesAltaAutoocupatDetailView.as_view(), name='resum_proces_alta_projecte_autoocupat'),

    url(r'^editar_sessio_moneda/(?P<pk>\d+)/$', SessioMonedaUpdateView.as_view(), name='editar_sessio_moneda'),

    url(r'^editar_sessio_acollida/(?P<pk>\d+)/$', SessioAcollidaUpdateView.as_view(), name='editar_sessio_acollida'),

    url(r'^llistat_sessio_acollida', SessioAcollidaListView.as_view(), name='llistat_sessio_acollida'),

    url(r'^crear_sessio_acollida', SessioAcollidaCreateView.as_view(), name='crear_sessio_acollida'),

    url(r'^llistat_sessio_moneda', SessioMonedaListView.as_view(), name='llistat_sessio_moneda'),

    url(r'^crear_sessio_moneda', SessioMonedaCreateView.as_view(), name='crear_sessio_moneda'),

    url(r'^generador_sessions/$',
        'generar_sessions',
        name='generador_sessions'),

    url(r'^sessions_del_mes/(?P<tipus>\w+)(/(?P<year>\d\d\d\d)/(?P<month>\d\d?))?$',
        'sessions_del_mes',
        name='sessions_del_mes'),

    url(r'^autoocupat/$',
        'proces_alta_projecte_autoocupat',
        name='proces_alta_projecte_autoocupat'),

    url(r'^autoocupat/(?P<id_proces>\d+)/$',
        'proces_alta_projecte_autoocupat',
        name='proces_alta_projecte_autoocupat'),

    url(r'^autoocupat/(?P<id_proces>\d+)/(?P<pas>\d+)/$',
        'proces_alta_projecte_autoocupat',
        name='proces_alta_projecte_autoocupat'),

    url(r'^autoocupat/llista-tasques/(?P<id_proces>\d+)/$',
        'proces_alta_projecte_autoocupat_llista_de_tasques',
        name='proces_alta_projecte_autoocupat-llista_de_tasques'),

    url(r'^autoocupat/llistat_proces_alta_autoocupat/$',
        'llistat_proces_alta_autoocupat',
        name='llistat_proces_alta_autoocupat'),

    url(r'^autoocupat/control-qualitat/$',
        'llistat_proces_alta_projecte_autoocupat_revisio_descripcions',
        name='llistat_proces_alta_projecte_autoocupat_revisio_descripcions'),

    url(r'^estadistiques_proces_alta_projecte_autoocupat/?$',
        'estadistiques_proces_alta_projecte_autoocupat',
        name='estadistiques_proces_alta_projecte_autoocupat'),

    url(r'^reassignacio_proces_alta_autoocupat/?$',
        'reassignacio_proces_alta_autoocupat',
        name='reassignacio_proces_alta_autoocupat'),

)

gestioci/urls.py
from django.conf import settings
from django.conf.urls import include, patterns, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = patterns(
    '',

    # Default Django Auth
    # https://docs.djangoproject.com/en/1.8/topics/auth/default/#built-in-auth-views
    url(r'^accounts/', include([
        url(r'^login/$', auth_views.login, name='login'),
        url(r'^logout/$', auth_views.logout, {'next_page': '/accounts/login/'}, name='logout'),

        url(r'^password/', include([
            url(r'^change/$', auth_views.password_change, name='password_change'),
            url(r'^change/done/$', auth_views.password_change_done, name='password_change_done'),

            url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.password_reset_confirm, name='password_reset_confirm'),
            url(r'^reset/complete/$', auth_views.password_reset_complete, name='password_reset_complete'),
            url(r'^reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
            url(r'^reset/$', auth_views.password_reset, { 'html_email_template_name': 'registration/password_reset_email.html' }, name='password_reset'),
        ])),
    ])),


    # Apps
    url(r'^socies/alta/', include('alta_socies.urls', namespace='alta_socies')),
    url(r'^socies/',      include('socies.urls', namespace='socies')),
    url(r'^facturacio/',  include('facturacio.urls', namespace='facturacio')),

    url(r'^admin/',       include(admin.site.urls)),

    url(r'^inici/$',       'inici.views.inici',                      name='inici'),
    url(r'^ge/$',          'inici.views.dashboard_gestio_economica', name='dashboard_gestio_economica'),
    url(r'^pao/$',         'facturacio.views.dashboard_facturacio',  name='dashboard_projecte_autoocupat'),
    url(r'^sc/$',          'socies.views.dashboard_socia_cooperativa',           name='dashboard_socia_cooperativa'),
    url(r'^style-guide/$', 'inici.views.styleguide',                 name='styleguide'),

    url(r'^/?$',            'inici.views.index',                      name='index'),
)

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns(
        '',
        (
            r'^media/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}
        ),
    )

# Implement docutils features
if settings.ENV == 'development':
    urlpatterns += patterns(
        '',
        ( r'^admin/doc/', include('django.contrib.admindocs.urls')),
        )

socies/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns(
    'socies.views',
    url(r'^cerca_persones/$', 'cerca_persones', name='cerca_persones'),
)

alta_socies/views.py
# coding=utf-8
import calendar
import json
from datetime import date, timedelta

from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.messages.views import SuccessMessageMixin
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import Group
from django.contrib import messages
from django.core.exceptions import SuspiciousOperation
from django.forms import modelformset_factory, formset_factory, SplitDateTimeWidget
from django.forms.models import modelform_factory
from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.template import RequestContext
from django.utils import timezone
from django.conf import settings
from django.db.models import Count
from django.http import HttpResponse
from django.template import loader, Context
from django.contrib.auth.models import User
from django.http.response import HttpResponseForbidden

from alta_socies.models import RegistreCanviProcesAltaAutoocupat
from .forms import GeneradorSessions, FormulariProjecte, FormulariDadesGeneralsProjecte, \
    FormulariDetallsMembreDeReferencia, FormulariAdrecaProjecteAutoocupat, \
    FormulariAltaProjecteAutoocupatSessioMoneda, FormulariAltaProjecteAutoocupatCessioUs, \
    FormulariAltaProjecteAutoocupatLloguer, FormulariAltresActivitatsProjecteAutoocupatFiraire, \
    FormulariAltresActivitatsProjecteAutoocupatNoFiraire, FormulariAltaConcessioActivitat, FormulariAltaAsseguranca, \
    FormulariAltaQuotes, FormulariFormaPagamentQuotesAutoocupat, FormulariCercaActualitzacioSeleccioPersones, \
    ForulariPas19, FormulariFotoProjecteAutoocupatFiraire, FormulariCercaProcesAltaAutoocupat, \
    FormulariReassignarProcesAltaAutoocupat, FormulariRebutjarProcesAltaAutoocupat, \
    FormulariDadesPersonalsSociaCooperativa, FormulariDadesAltaSociaCooperativa, \
    FormulariResumSociaCooperativa, FormulariDadesGeneralsProjecteCollectiu, \
    FormulariDadesConcretesProjecteCollectiu

from gestioci.settings import auth_groups
from .models import SessioAlta, SessioAvaluacio, ProcesAltaAutoocupat, SessioAcollida, \
    PeticioConcessioActivitat, PeticioAsseguranca, SessioMoneda, SociaCooperativa, SociaAfi, \
    ProjecteCollectiu
from socies.models import Persona, AdrecaProjecteAutoocupat, HabilitatsContribucionsPersona, \
    Habilitat, ContribucioCIC, Activitat, AdrecaProjecteCollectiu, PersonaUsuaria
from empreses.models import Cooperativa
from gestioci.formats import dow_names
from gestioci.thumbnails import create_thumbnail
from projectes.models import FotoProjecteAutoocupatFiraire, ProjecteAutoocupat, PolissaAsseguranca



def _ordenar_queryset_sessions(queryset):
    """
    Ordena un queryset de Sessio (o classes derivades) amb l'objectiu de poder
    agrupar al template. Atenció que el queryset retornat té camps 'extra' que
    calen per fer la ordenació a Postgres.
    :param queryset: queryset de Sessio o derivats
    :return: queryset amb 'extras' ordenat de la següent manera:
        1. per any i mes (descendent)
        2. per dia del mes
        3. per ubicació
        4. per hora i minut (i segons etc.)
    """

    queryset = queryset.extra(
        select={
            'x_year_month': 'date_trunc(\'month\', data)',
            'x_dom':        'extract(day from data)',
            'x_time':       'extract(epoch from data)'
        }
    )

    queryset = queryset.order_by('-x_year_month', 'x_dom', 'ubicacio__nom', 'x_time')

    return queryset


def _buscar_processos_alta_autoocupat(criteri):

    resultats = ProcesAltaAutoocupat.objects

    responsable = criteri.get('per_responsable', None)
    if responsable:
        responsable = int(responsable)
    email = criteri.get('per_email', None)
    nom = criteri.get('per_nom', None)
    estat = criteri.get('per_estat', None)
    if estat == '*':
        estat = None

    cerca = False  # per saber al template si s'ha executat una cerca o si acabem d'arribar a la "pàgina"

    if responsable:
        resultats = resultats.filter(responsable=responsable).order_by('nom')
        cerca = True

    if email:
        resultats = resultats.filter(email__icontains=email).order_by('email')
        cerca = True

    if nom:
        resultats = resultats.filter(nom__icontains=nom).order_by('nom')
        cerca = True

    if estat:
        resultats = resultats.filter(resolucio=estat)
        cerca = True

    return resultats, cerca


@login_required
def rebutjar_proces_alta_autoocupat(request, id_proces):

    proces = ProcesAltaAutoocupat.objects.get(id=id_proces)

    if not request.user.id == proces.responsable.id and not is_user_supervisora_alta(request.user):

        messages.error(request, u"No tens permís per rebutjar aquest projecte autoocupat.")
        return redirect('inici')

    if request.method == 'POST':

        form = FormulariRebutjarProcesAltaAutoocupat(data=request.POST)

        if form.is_valid():
            proces.resolucio = ProcesAltaAutoocupat.RESOLUCIO_REBUTJAT
            proces.data_resolucio = timezone.localtime(timezone.now())
            proces.comentaris_resolucio = form.cleaned_data.get('motiu')
            proces.resolucio_usuaria = request.user
            proces.save()

            messages.success(request, u"Has rebutjat el projecte autoocupat.")

            return redirect('dashboard_gestio_economica')

    if request.method == 'GET':

        form = FormulariRebutjarProcesAltaAutoocupat()

    return render(
        request,
        'alta_socies/autoocupat/rebutjar.html',
        dict(
            form=form,
            proces=proces,
        )
    )


def is_user_responsable_alta(user):
    """
    function that returns True when user belongs
    to RESPONSABLE_ALTA group
    """
    return user.groups.filter(name=auth_groups.RESPONSABLES_ALTA).exists()


class FilterResponsablesAltaMixin(object):
    """
    Mixin per filtrar la llista d'opcions al widget del camp "responsable_alta"
    de manera que només ofereix usuaris membres del grup RESPONSABLES_ALTA
    """
    def get_context_data(self, **kwargs):
        context = super(FilterResponsablesAltaMixin, self).get_context_data(**kwargs)
        context['form'].fields['responsable_alta'].queryset = User.objects.filter(
            groups__name=auth_groups.RESPONSABLES_ALTA)
        return context


def is_user_exporter(user):
    return user.groups.filter(name=auth_groups.EXPORTADORES).exists()


# TODO this fully overlaps the checks in gci_tags; I bet there is something native in django th handle this.
def is_user_supervisora_alta(user):
    return user.groups.filter(name=auth_groups.SUPERVISORES_ALTA).exists()


@login_required
@user_passes_test(is_user_exporter)
def exportar_a_csv(request):
    """ 
    Vista per exportar els processos d'alta de projecte
    autoocupat en format CSV ("cap al transversal")
    """

    def trobar_activitats_procesaltaautoocupat(projecte):
        """
        Find the names of the Activitat that are "linked" to "projecte"
        :param projecte: either a ProcesAltaAutoocupat or a ProjecteAutoocupat
        :return: list with the names of the Activitat
        """
        resultat = projecte.altres_activitats.all()
        for a in projecte.adreces.all():
            resultat |= a.activitats.all()
        return list(resultat.distinct().values_list('nom', flat=True))

    def trobar_habilitats_procesaltaautoocupat(projecte):
        """
        Find the names of the Habilitat that are "linked" to "membres de referència" in "projecte"
        :param projecte: either a ProcesAltaAutoocupat or a ProjecteAutoocupat
        :return: list with the names of the Habilitat
        """
        resultat = Habilitat.objects.none()
        mr = projecte.membres_de_referencia.all()
        hcp = HabilitatsContribucionsPersona.objects.filter(persona__in=mr)
        for h in hcp:
            resultat |= h.habilitats.all()
        return list(resultat.distinct().values_list('nom', flat=True))

    d = timezone.localtime(timezone.now()).date().isoformat()
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="projectes-%s.csv"' % d

    header = [
        u"Data de resolució",
        u"Compte COOP",
        u"Cooperativa",
        u"Email",
        u"Telèfon",
        u"Adreça",
        u"CP",
        u"Població",
        u"Comarca",
        u"mrNom",
        u"mrCognoms",
        u"mrDNI",
        u"Tipus",
        u"Pas",  # TODO: quan tirem de ProjecteAutoocupat, aquest camp no tindrà sentit
        u"Activitats",
        u"Habilitats",
    ]

    csv_data = [header]

    for proces in ProcesAltaAutoocupat.objects.all().exclude(resolucio=ProcesAltaAutoocupat.RESOLUCIO_REBUTJAT).order_by('id'):

        #####################################################################################
        #
        # Farem servir la data de l'últim "pas 20" com a "data d'alta" si el procés d'alta
        # no s'ha "acceptat", donat que ara mateix a producció estan en aquest estat tots els
        # processos. Quan es desplegui la nova versió a producció i s'acceptin els processos,
        # ja no caldrà aquest bloc de codi.

        # de fet, ara mateix probablement tindria sentit treure de la llista el processos que
        # no han passat el pas 20 (no existeix un RegistreCanviProcesAltaAutoocupat del 20 al 20)
        # o inclús marcar com a "acceptat" els processos que estan en aquest estat.
        # TODO: proposar marcar com a "acceptat" els processos que tenen una transició 20 -> 20 i que estan al pas 20

        # select proces_id, max(updated_at) from alta_socies_registrecanviprocesaltaautoocupat
        #        where pas_origen = 20 and pas_origen=20 group by proces_id;

        data_alta = None
        if proces.data_resolucio:

alta_socies/templates/alta_socies/cita_nou_projecte_autoocupat.html
{%  extends "gci.html" %}

{% block main %}
<h1>Assignació de cites per alta de projecte autoocupat</h1>
<form name="cita_nou_projecte_autoocupat" method="POST">{% csrf_token %}

    <table>
        {{ form_projecte.as_table }}
        {{ form_cites.as_table }}
    </table>

    <input type="submit" value="enregistrar">

</form>

{% endblock %}

alta_socies/templates/alta_socies/detalls_i_validacio_projectes_pendents.html
{% extends 'layout.html' %}
{% load gci_tags %}

{% block content %}
<div class="row">
  <div class="medium-10 columns">
    <h1>{{ title }}</h1>
    <p> Cuan validis, haurás donat per entredit que el projecte ha pagat la quota d'alta i que les dades son valides </p>
  </div>
</div>
<div class="row">
  <div class="medium-12 columns">
    <fieldset>
      <legend>
	Dades del projecte
      </legend>
      <div class="row">
	<div class="medium-3 columns">
	  <strong>Nom: </strong><p>{{ projecte.nom }}</p>
	</div>
	<div class="medium-3 columns">
	  <strong>Website: </strong><p>{{ projecte.website }}</p>
	</div>
	<div class="medium-3 columns">
	  <strong>Email: </strong><p>{{ projecte.email }}</p>
	</div>
	<div class="medium-3 columns">
	  <strong>Telefon: </strong><p>{{ projecte.telefon }}</p>
	</div>
      </div>
      <div class="row">
	<div class="medium-3 columns">
	  <strong>Descripcio: </strong><p>{{ projecte.descripcio }}</p>
	</div>
	<div class="medium-3 columns">
	  <strong>Adreça: </strong><p>{{ projecte.adreca.adreca }}</p>
	</div>
	<div class="medium-3 columns">
	  <strong>Tipus: </strong><p>{{ projecte.get_tipus_projecte_display }}</p>
	</div>
	<div class="medium-3 columns">
	  <strong>Cobertura legal: </strong><p>{{ projecte.necessita_cobertura_legal }}</p>
	</div>
      </div>
      <div class="row">
	<div class="medium-3 medium-centered columns">
	  <strong>Forma de pagament: </strong><p>{{ projecte.get_quota_alta_forma_pagament_display }}</p>
	</div>
      </div>
    </fieldset>
  </div>
</div>
<div class="row">
  <div class="medium-12 columns">
    <fieldset>
      <legend>
	Dades mancants
      </legend>
      <div class="row">
	<div class="medium-3 columns medium-centered">
	  <form method="post">
	    {% csrf_token %}
	    {% non_field_errors form %}
	    {% form_field form.compte_CES_assignat %}
	    <button type="submit" class="radius success">Validar</button>
	  </form>
	</div>
      </div>
    </fieldset>
  </div>
</div>
{% endblock content %}

	  
      

alta_socies/templates/alta_socies/detalls_i_validacio_socies_pendents.html
{% extends 'layout.html' %}
{% load gci_tags %}

{% block content %}
<div class="row">
  <div class="medium-10 columns">
    <h1>{{ title }}</h1>
    <p> Cuan validis, haurás donat per entredit que la socia ha pagat la quota d'alta i que les dades son valides </p>
  </div>
</div>
<div class="row">
  <div class="medium-12 columns">
    <fieldset>
      <legend>
	Dades de la socia
      </legend>
      <div class="row">
	<div class="medium-3 columns">
	  <strong>Nom: </strong><p>{{ socia.socia.nom }}</p>
	</div>
	<div class="medium-3 columns">
	  <strong>Primer cognom: </strong><p>{{ socia.socia.cognom1 }}</p>
	</div>
	<div class="medium-3 columns">
	  <strong>Segon cognom: </strong><p>{{ socia.socia.cognom2 }}</p>
	</div>
	<div class="medium-3 columns">
	  <strong>Pseudonim: </strong><p>{{ socia.socia.pseudonim }}</p>
	</div>
      </div>
      <div class="row">
	<div class="medium-3 columns">
	  <strong>Email: </strong><p>{{ socia.socia.email }}</p>
	</div>
	<div class="medium-3 columns">
	  <strong>Telefon: </strong><p>{{ socia.socia.telefon }}</p>
	</div>
	<div class="medium-3 columns">
	  <strong>Dni: </strong><p>{{ socia.socia.dni }}</p>
	</div>
	<div class="medium-3 columns">
	  <strong>Compte iCES: </strong><p>{{ socia.socia.compte_integralces }}</p>
	</div>
      </div>
      <div class="row">
	<div class="medium-3 medium-centered columns">
	  <strong>Forma de pagament: </strong><p>{{ socia.get_quota_alta_forma_pagament_display }}</p>
	</div>
      </div>
    </fieldset>
  </div>
</div>
<div class="row">
  <div class="medium-12 columns">
    <fieldset>
      <legend>
	Dades mancants
      </legend>
      <div class="row">
	<div class="medium-3 columns medium-centered">
	  <form method="post">
	    {% csrf_token %}
	    {% non_field_errors form %}
	    {% form_field form.compte_CES_assignat %}
	    <button type="submit" class="radius success">Validar</button>
	  </form>
	</div>
      </div>
    </fieldset>
  </div>
</div>
{% endblock content %}

	  
      

alta_socies/templates/alta_socies/formulari_projecte_collectiu_dades_concretes.html
{% extends 'layout.html' %}
{% load gci_tags %}

{% block content %}
<div class="row">
  <div class="medium-10 large-10 columns">
    <h1>{{ title }}</h1>
    <h3>{{ descripcio }}</h3>
  </div>
</div>
<br />
<div class="row">
  <div class="medium-12 large-12 columns">
    <form method="post">
      {% csrf_token %}
      {% non_field_errors form %}
      <fieldset>
	<div class="row">
	  <div class="medium-12 columns">
	    {% form_field form.membre_de_referencia %}
	  </div>
	</div>
      </fieldset>
      <fieldset>
	<div class="row">
	  <div class="medium-12 columns">
	    <p> La diferencia entre els diferents tipus de projecte es: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."</p>
	  </div>
	</div>
	<div class="row">
	  <div class="medium-12 columns">
	    {% form_field form.tipus_projecte %}
	  </div>
	</div>
      </fieldset>
      <fieldset>
	<legend>
	  Quota d'alta i cobertura legal
	</legend>
	<div class="row">
	  <div class="medium-6 columns">
	    {% form_field form.formes_pagament_quota_alta %}
	  </div>
	  <div class="medium-6 columns">
	    {% form_field form.necessita_cobertura_legal %}
	  </div>
	</div>
      </fieldset>
      <fieldset>
	<button type="submit" class="success radius right">Segueix</button>
      </fieldset>
    </form>
  </div>
</div>
{% endblock content %}

alta_socies/templates/alta_socies/formulari_sessio.html
{% extends "simple.html" %}
{% load gci_tags %}

{% block content %}
    <h1>{{ view.title }}</h1>
    <form method="post">
        {% csrf_token %}
        {% non_field_errors form %}
        <div class="row">
            <div class="medium-6 columns">
                {% form_field form.ubicacio %}
            </div>
            <div class="medium-6 columns">
                {% form_field form.responsable_alta %}
            </div>
        </div>
        <div class="row">
            <div class="medium-6 columns">
                {% form_field form.data %}
            </div>
            <div class="medium-6 columns">
                {% form_field form.duracio %}
            </div>
        </div>
        <button class="radius button" type="submit">{{ view.action_label }}</button>
    </form>
{% endblock %}

alta_socies/templates/alta_socies/llistat_projectes_pendents.html
{% extends 'layout.html' %}

{% block content %}
<div class="row">
  <div class="medium-10 columns">
    <h1>{{ title }}</h1>
  </div>
</div>
<div class="row">
  <div class="medium-12 columns">
    <table>
      <thead>
	<tr>
	  <th>
	    Nom del Projecte
	  </th>
	  <th>
	    Membre de referencia
	  </th>
	  <th>
	    Detalls i validació
	  </th>
	</tr>
      </thead>
      <tbody>
	{% for projecte in projectes %}
	<tr>
	  <td>{{ projecte.nom }} </td>
	  <td>{{ projecte.membre_de_referencia }} </td>
	  <td>
	    <a href="{% url 'alta_socies:validar_projecte_pendent' projecte.id %}" class="round button small"><i class="fa fa-fw fa-check-circle-o"></i></a>
	  </td>
	</tr>
	{% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock content %}

alta_socies/templates/alta_socies/llistat_socies_pendents.html
{% extends 'layout.html' %}

{% block content %}
<div class="row">
  <div class="medium-10 columns">
    <h1>{{ title }}</h1>
  </div>
</div>
<div class="row">
  <div class="medium-12 columns">
    <table>
      <thead>
	<tr>
	  <th>
	    Nom de la Socia
	  </th>
	  <th>
	    Detalls i validació
	  </th>
	</tr>
      </thead>
      <tbody>
	{% for socia in socies %}
	<tr>
	  <td>{{ socia.socia.nom_sencer }} </td>
	  <td>
	    <a href="{% url 'alta_socies:validar_socia_pendent' socia.id %}" class="round button small"><i class="fa fa-fw fa-check-circle-o"></i></a>
	  </td>
	</tr>
	{% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock content %}